config/routes.rb
Isitfedoraruby::Application.routes.draw do

  root to: 'home#show'

  get 'about', to: 'static_pages#about'
  get 'contact', to: 'static_pages#contact'

  get 'searches/suggest_gems' => 'searches#suggest_gems'
  post 'searches/' => 'searches#redirect'
  get 'searches/:id' => 'searches#index'

  resources :fedorarpms, only: [:index, :show] do
    member do
      get :full_deps
      get :full_dependencies
      get :full_dependents
      get :by_owner
      get :badge
      get :not_found
    end
  end

  resources :rubygems, only: [:index, :show]

  resources :stats, only: [:index] do
    get :gemfile_tool, on: :collection
    get :user_rpms
    get :timeline
    get :tljson
    get :user_rpms_data
    post :gemfile_tool, on: :collection
  end

  # unless Rails.application.config.consider_all_requests_local
  get '*not_found', to: 'errors#error_404'
  #  end

end

app/models/fedora_rpm.rb
# == Schema Information
#
# Table name: fedora_rpms
#
#  id                  :integer          not null, primary key
#  name                :string(255)      not null
#  source_uri          :string(255)
#  last_commit_message :string(255)
#  created_at          :datetime
#  updated_at          :datetime
#  owner               :string(255)
#  last_committer      :string(255)
#  last_commit_date    :datetime
#  last_commit_sha     :string(255)
#  homepage            :string(255)
#  ruby_gem_id         :integer
#  commits             :integer
#  owner_email         :string(255)
#  summary             :text(255)
#  description         :text(255)
#

require 'versionomy'
require 'xmlrpc/client'
require 'bicho'
require 'open-uri'

# Used for packaged gems in Fedora
# - Retrieves dependencies
# - Retrieves koji builds
# - Retrieves bugs in bugzilla.redhat.com
# - Retrieves meta information about the gem
class FedoraRpm < ActiveRecord::Base
  include ActionView::Helpers::DateHelper

  validates :name, uniqueness: true
  validates :name, presence: true

  belongs_to :ruby_gem
  has_many :rpm_versions, dependent: :destroy
  has_many :bugs, -> { order 'bz_id desc' }, dependent: :destroy
  has_many :koji_builds, -> { order 'build_id desc' }, dependent: :destroy
  has_many :dependencies, -> { order 'created_at desc' }, as: :package,
                                                          dependent: :destroy
  scope :most_recent, -> { order 'last_commit_date desc' }

  def to_param
    name
  end

  def shortname
    name.gsub(/rubygem-/, '')
  end

  def self.fedora_versions

    # Read file which contains latest fedora version.
    # See lib/rawhide_version.rb
    # Get latest version with: "rake fedora:rawhide:create"
    file = File.open(Rails.root + 'public/version/rawhide', 'r')
    version = file.read.to_i

    { 'Rawhide'   => 'master',
      "Fedora #{version - 1}" => "f#{version - 1}",
      "Fedora #{version - 2}" => "f#{version - 2}"
    }
  end

  def up_to_date?
    rawhide_version = rpm_versions.find { |rv| rv.fedora_version == 'Rawhide' }
    return false if rawhide_version.nil? ||
                    rawhide_version.rpm_version.nil? ||
                    ruby_gem.nil? || ruby_gem.version.nil?
    begin
      Versionomy.parse(rawhide_version.rpm_version) >=
        Versionomy.parse(ruby_gem.version)
    rescue Versionomy::Errors::ParseError
      false
    end
  end

  def base_uri
    'http://pkgs.fedoraproject.org/cgit/'
  end

  def spec_uri
    "#{base_uri}#{name}.git/tree/#{name}.spec"
  end

  # Get and store the commits metadata in database.
  def commits_metadata(name)
    pkg = Pkgwat.get_changelog(name)
    self.commits = pkg.count
    self.last_commit_message = pkg.first['text'].gsub(/^- /, '')
    self.last_committer = pkg.first['author']
    self.last_commit_date = pkg.first['date']
  end

  # Retrieve version for a specific release.
  # fedora_version can be one of three:
  # - "Rawhide"
  # - "Fedora 20"
  # - "Fedora 19"
  # Example:
  #   > name = 'rubygem-rails'
  #   > rpm = FedoraRpm.new
  #   > rpm.retrieve_version("Rawhide")
  #   > "4.1.4"
  def retrieve_version(fedora_version)
    rpm = Pkgwat.get_releases(name).select do |r|
      r['release'] == fedora_version
    end
    if !!(rpm.first['stable_version'].match(/href/))
      rpm.first['stable_version'].scan(/>.*-/)[0].gsub(/[>-]/, '')
    else
      rpm.first['stable_version'].split('-').first
    end
  end

  # Store the rpm versions of a given package of
  # all supported Fedora versions in rpm_versions table.
  def store_all_versions
    rpm_versions.clear
    self.class.fedora_versions.each do |version_title, version_git|
      rpm_version = retrieve_version(version_title)
      rv = RpmVersion.new
      rv.rpm_version = rpm_version
      rv.fedora_version = version_title
      rv.patched = patched?(version_git)
      rpm_versions << rv
    end
  end

  # Get a string of all packaged versions of a rubygem package.
  # It calls RpmVersion#to_s, see app/models/rpm_version.rb.
  # Example output in rails console:
  #   > name = 'rubygem-rails'
  #   > rpm = FedoraRpm.find_by(name: name);
  #   > rpm.versions
  #   > "4.1.4 (Rawhide/not patched), 4.0.0 (Fedora 20/not patched),
  #      3.2.13 (Fedora 19/not patched)"
  def versions
    rpm_versions.map { |rpm_version| rpm_version.to_s }.join(', ')
  end

  # Query the rpm_versions table for the package version of a given
  # Fedora version.
  # fedora_version can be one of three:
  # - "Rawhide"
  # - "Fedora 20"
  # - "Fedora 19"
  def version_for(fedora_version)
    version = rpm_versions.find { |rv| rv.fedora_version == fedora_version }
    version.rpm_version unless version.nil?
  end

  # Check if a version is valid: major.minor.patch
  def version_valid?(version)
    Versionomy.parse(version)
    true
  rescue Versionomy::Errors::ParseError
    false
  end

  # Check if any version is patched.
  # This then is passed to the view fedorarpms#index.
  def any_patched?
    rpm_versions.any? { |rpm_version| rpm_version.patched }
  end

  # Check if a version is patched by scrapping the spec file.
  # version_git can be one of the following:
  # - "master" for the rawhide version
  # - "fN" where N the Fedora version number, eg: 22,21,20,19,etc.
  # If no parameter is passed, it defaults to master.
  def patched?(version_git = 'master')
    spec_url = "#{base_uri}#{name}.git/plain/#{name}.spec?h=#{version_git}"
    rpm_spec = open(spec_url).read
    rpm_spec.scan(/\nPatch0:\s*.*\n/).size != 0
  end

  # Get the alias mail for the package.
  # It is forwarded to the real packagers' mail that is
  # registered with their FAS name.
  def get_owner_email
    "#{name}-owner@fedoraproject.org"
  end

  def obfuscated_email
    fedora_user.to_s.gsub('@', ' AT ').gsub('.', ' DOT ')
  end

  def fas_name
    Pkgwat.get_packages(name)[0]['devel_owner']
  end

  def retrieve_homepage(name)
    Pkgwat.get_packages(name)[0]['upstream_url']
  end

  def retrieve_dependencies
    dependencies.clear
    spec_url = "#{base_uri}#{name}.git/plain/#{name}.spec?h=master"
    rpm_spec = open(spec_url).read
    rpm_spec.split("\n").each do |line|
      mr = line.match(/^Requires:\s*rubygem\(([^\s]*)\)\s*(.*)$/)
      env = 'runtime'
      if mr.nil?
        mr = line.match(/^BuildRequires:\s*rubygem\(([^\s]*)\)\s*(.*)$/)
        env = 'development'
      end
      if mr
        d = Dependency.new
        d.dependent = mr.captures.first
        d.dependent_version = mr.captures.last.gsub(/(%{version})/, retrieve_version('Rawhide'))
        d.environment = env
        dependencies << d
      end
    end
  end

  def json_dependencies(packages = [])
    children = []
    dependency_packages.each do |p|
      unless packages.include?(p)
        packages << p
        children << p.json_dependencies(packages)
      end
    end
    { name: shortname, children: children }
  end

  def json_dependents(packages = [])
    children = []
    dependent_packages.each do |p|
      unless packages.include?(p)
        packages << p
        children << p.json_dependents(packages)
      end
    end
    { name: shortname, children: children }
  end

  # Returns an array of dependencies in a FedoraRpm format
  def dependency_packages
    dependencies.map do |d|
      FedoraRpm.where(name: "rubygem-#{d.dependent}").to_a
    end.compact.flatten
  end

  def dependent_packages
    Dependency.where(dependent: shortname).map do |d|
      d.package if d.package.is_a?(FedoraRpm)
    end.compact
  end

  def retrieve_gem
    gem_name = shortname
    puts "Retrieving gem #{gem_name} data"
    self.ruby_gem = RubyGem.where(name: gem_name).first_or_create
    ruby_gem.update_from_source
    ruby_gem.has_rpm = true
  end

  def retrieve_bugs
    bugs.clear
    open_bugs = Pkgwat.get_bugs(name)

    open_bugs.reject { |b| b['release'].match(/EPEL/) }.each do |b|
      bug = Bug.new
      bug.name = b['description']
      bug.bz_id = b['id']
      bug.last_updated = b['last_modified']
      bug.is_review = true if b['name'] =~ /^Review Request.*#{name}\s.*$/
      bugs << bug
    end
  end

  def retrieve_builds
    koji_builds.clear

    version = RawhideVersion.version

    # Retrieve only latest 3 Fedora versions of builds
    koji_builds = Pkgwat.get_builds(name).select do |build|
      !!(build['nvr'] =~ /fc(#{version}|#{version - 1}|#{version - 2})/)
    end

    koji_builds.each do |build|
      bld = KojiBuild.new
      bld.name = build['nvr']
      bld.build_id = build['build_id']
      self.koji_builds << bld
    end
  end

  def update_commits
    commits_metadata(name)
    self.updated_at = Time.now
    save!
  rescue => e
    puts "Updating #{name} failed due to #{e}"
  end

  def update_dependencies
    retrieve_dependencies
    self.updated_at = Time.now
    save!
  rescue => e
    puts "Updating #{name} failed due to #{e}"
  end

  def update_versions
    store_all_versions
    self.updated_at = Time.now
    save!
  rescue => e
    puts "Updating #{name} failed due to #{e}"
  end

  def update_gem
    retrieve_gem
    self.updated_at = Time.now
    save!
  rescue => e
    puts "Updating #{name} failed due to #{e}"
  end

  def update_bugs
    retrieve_bugs
    self.updated_at = Time.now
    save!
  rescue => e
    puts "Updating #{name} failed due to #{e}"
  end

  def update_builds
    retrieve_builds
    self.updated_at = Time.now
    save!
  rescue => e
    puts "Updating #{name} failed due to #{e}"
  end

  def update_from_source
    update_commits
    update_specs
    update_gem
    update_bugs
    update_builds
  end

  def rpm_name
    name
  end

  def self.search(search)
    # search_cond = "%" + search.to_s + "%"
    # search_cond = search.to_s
    if search.nil? || search.blank?
      self
    else
      where('name LIKE ?', 'rubygem-' + search.strip)
    end
  end

  def last_commit_date_in_words
    "#{time_ago_in_words(last_commit_date)} ago" unless last_commit_date.nil?
  end
end

app/controllers/fedorarpms_controller.rb
class FedorarpmsController < ApplicationController
  helper_method :sort_column, :sort_direction

  def index
    @page_title = 'Fedora RPMs'
    @rpms = FedoraRpm.paginate(page: params[:page], per_page: 50)
                     .order(sort_column + ' ' + sort_direction)
  end

  def show
    @name = params[:id]
    @rpm = FedoraRpm.find_by_name! @name
    @page_title = @rpm.name
    @dependencies = @rpm.dependency_packages.uniq
    @dependents = @rpm.dependent_packages.uniq
    # We can register a global error handler inside the application controller for this.
    rescue ActiveRecord::RecordNotFound
      redirect_to action: 'not_found'
  end

  def not_found
    @rpm = params[:id]
    @results = FedoraRpm.where('name LIKE ?', "%#{@rpm}%")
  end

  def full_deps
    @name = params[:id]
    @rpm = FedoraRpm.find_by_name(@name)
    respond_to do |format|
      format.html
    end
  end

  def full_dependencies
    @name = params[:id]
    @rpm = FedoraRpm.find_by_name(@name)
    respond_to do |format|
      format.json { render json: @rpm.json_dependencies }
    end
  end

  def full_dependents
    @name = params[:id]
    @rpm = FedoraRpm.find_by_name(@name)
    respond_to do |format|
      format.json { render json: @rpm.json_dependents }
    end
  end

  def by_owner
    @name = params[:id]
    @rpms = FedoraRpm.where('owner LIKE ?', @name)
    @uptodate = @rpms.select { |rpm| rpm.up_to_date? }
    @outdated = @rpms.reject { |rpm| rpm.up_to_date? }
  end

  def badge
    @user_name = params[:id]
    rpms = FedoraRpm.where('owner LIKE ?', @user_name)
    @total = rpms.size
    @commits = 0
    @most = nil
    rpms.each do |rpm|
      @commits += rpm.commits
      @most = rpm if @most.nil? || rpm.commits > @most.commits
    end
    @most = @most.shortname
    render layout: false
  end

  private

  def sort_column
    %w(name commits last_commit_date owner).include?(params[:sort]) ?
        params[:sort] : 'name'
  end

  def sort_direction
    %w(asc desc).include?(params[:direction]) ? params[:direction] : 'asc'
  end
end

app/views/fedorarpms/badge.html.haml
:css
  div.badge {
  text-shadow: white 1px 1px 0px;#255591;
  border: 1px solid #D4D4D4;
  width: 150px;
  border-bottom: 2px solid #255591;
  background: -webkit-gradient(linear, left bottom, left top, from(#A9C8DA), to(white));
  line-height: 130%;
  padding: 1px 9px 2px;
  border-radius: 9px;
  font-size: 12px;
  font-weight: bold;
  color: #255591;
  }

  #username  {
    font-family: "Cantarell", sans-serif;
  }
  #rpms, #commits, #popular {
    font-size: 0.8em;
    font-family: "Cantarell", sans-serif;
  }
  #maintainer {
    font-size: 1.3em;
    font-family: "Cantarell", sans-serif;
  }

.badge
  %h2#username{:align => "center"} #{@user_name}</br>
  %a#rpms rpms: #{@commits}</br>
  %a#commits commits: #{@total}</br>
  %a#popular Most popular rpm: #{@most}</br>
  %a#maintainer
    = image_tag('Maintainer.png')

app/views/fedorarpms/by_owner.html.haml
.bs-callout-active.bs-callout
  %h2= _('All rubygems maintained by user %{name}') % { :name => @name}
  %p Total: #{@rpms.count}
  %p Up to date: #{@uptodate.count}
  %p Outdated: #{@outdated.count}
  %p
    = link_to _('See it in a nice bubble chart'), stats_path + "/" + @name + "/user_rpms"
  %p
    Green lines indicate rpms that are up to date, red ones are outdated.

.table-responsive
  %table.table.table-hover.table-condensed
    %thead
      %tr.warning
        %th= sortable _('Rpm')
        %th= _('Upstream')
        %th= _('Rawhide')
        %th= _('Git Commits')

    %tbody
      - @rpms.each do |rpm|
        %tr{class: rpm.up_to_date? ? 'success' : 'danger'}
          %td= link_to rpm.name, fedorarpm_path(rpm.name)
          %td= rpm.ruby_gem.version if rpm.ruby_gem
          %td= rpm.version_for 'Rawhide'
          %td= rpm.commits

app/views/fedorarpms/full_deps.html.haml
.d3_chart_container
  %h2= link_to(@rpm.name, fedorarpm_path(@rpm.name))
  %h3= _("Dependencies")
  #dependent_chart

.d3_chart_container
  %h3= _('Dependent Packages')
  #dependency_chart

:javascript
  function load_chart(json_url, div_id, width, height, invert){
    var tree1 = d3.layout.tree().size([width, height]);
                   //.separation(function(a, b) { return (a.parent == b.parent ? 1 : 2) / a.depth; });

    var diagonal = d3.svg.diagonal().
                      projection(function(d) { return [d.x, d.y]; });

    var translate = invert ? "rotate(180) translate(-"+width+",-"+(height+10)+")" :
                             "translate(0,10)";
    var t1 = d3.select(div_id).append("svg")
                 .attr("width", width).attr("height", height+80)
                 .append("g")
                 .attr("transform", translate);

    d3.json(json_url, function(json) {
      var nodes = tree1.nodes(json);

      var link = t1.selectAll("path.link")
                   .data(tree1.links(nodes))
                   .enter().append("path")
                   .attr("class", "link")
                   .attr("d", diagonal);

      var rotate = invert ? 230 : 30;
      var node = t1.selectAll("g.node")
                    .data(nodes)
                    .enter().append("g")
                    .attr("class", "node")
                    .attr("transform", function(d) { return "translate(" + d.x + ", " + d.y + ") rotate("+rotate+")"; })

      node.append("circle").attr("r", 4.5);

      node.append("text")
          .attr("dx", function(d) { return d.children ? 8 : -8; })
          .attr("dy", ".73em")
          .attr("text-anchor", function(d) { return d.children ? "start" : "end"; })
          .on("click", function(d, i) { window.location = '/fedorarpms/rubygem-' + d.name; })
          .on("mouseover", function() { document.body.style.cursor = 'pointer'; })
          .on("mouseout", function() { document.body.style.cursor = 'default'; })
          .text(function(d) { return d.name; });
    });
  }

  load_chart("/fedorarpms/#{@name}/full_dependencies.json", "#dependency_chart", 800, 900, false);
  load_chart("/fedorarpms/#{@name}/full_dependents.json",   "#dependent_chart", 800, 1200, true);

app/views/fedorarpms/index.html.haml
%h2= @page_title
%h4 There are currently #{@rpms.count} rubygems packaged for Fedora.
%p
.table-responsive
  %table.table.table-hover.table-condensed
    %thead
      %tr.warning
        %th= sortable 'name', _('Name')
        - FedoraRpm.fedora_versions.each do |t, g|
          %th= t
        %th= _('Upstream')
        %th= sortable 'commits', _('Commits')
        %th= sortable 'last_commit_date', _('Last Commit')
        %th= _('Patched?')
        %th= sortable 'owner', _('Owner')

    %tbody
      - @rpms.each do |rpm|
        %tr{class: rpm.up_to_date? ? 'success' : 'danger'}
          %td= link_to rpm.shortname.truncate(35), fedorarpm_path(rpm.name)
          -FedoraRpm.fedora_versions.each do |t, g|
            %td= rpm.version_for(t)
          %td= rpm.ruby_gem.version
          %td= rpm.commits
          %td= rpm.last_commit_date_in_words
          %td
            - if rpm.any_patched?
              %span.glyphicon.glyphicon-ok
          %td
            - unless rpm.owner.nil?
              =link_to rpm.owner, fedorarpm_path(rpm.owner + '/by_owner')

%div.pagination
  = will_paginate @rpms

app/views/fedorarpms/not_found.html.haml
%h1 RPM Not Found

Sorry, we couldn't find
%b=@rpm
as a Fedora RPM; please check your URL and try again.
%br/
%br/
- if @results != []

  %table.table.table-striped.table-condensed
    %thead
      %tr
        %th Did you mean:

    %tbody
      - @results.each do |r|
        %tr
          %td= link_to r.rpm_name, fedorarpm_path(r.rpm_name)

app/views/fedorarpms/show.html.haml
.bs-callout-info.bs-callout
  %h2= @rpm.name
  %p
  - unless @rpm.summary.blank?
    = "#{@rpm.summary}"

-#  = link_to _('Timeline (Bugs and Versions)'), stats_path + "/" + @name + "/timeline"

.span12
  %ul.nav.nav-tabs#fedorarpm-show{role: 'tablist'}
    %li.active
      = link_to 'Basic info', '#info', { data: {toggle: 'tab'}, role: 'tab' }
    %li
      = link_to 'Versions', '#versions', { data: {toggle: 'tab'}, role: 'tab' }
    %li
      = link_to 'Dependencies', '#dependencies', { data: {toggle: 'tab'}, role: 'tab' }
    %li
      = link_to 'Bugs', '#bugs', { data: {toggle: 'tab'}, role: 'tab' }
    %li
      = link_to 'Builds', '#builds', { data: {toggle: 'tab'}, role: 'tab' }
  %p
  .tab-content.span12#fedorarpm-show
    .tab-pane.fade.in.active#info
      - unless @rpm.ruby_gem.nil?
        = button_to "#{@rpm.ruby_gem.name}.gem", rubygem_path(@rpm.ruby_gem.name),
        :class => 'btn btn-success', :type => 'button', :method => :get
      %br
      %p
        Up to date:
        - if @rpm.up_to_date?
          %span.label.label-success= _('Yes')
        - else
          %span.label.label-danger= _('No')
      %p
        Gitweb repository:
        = link_to @rpm.source_uri, @rpm.source_uri
      %p
        SPEC file:
        = link_to @rpm.spec_uri, @rpm.spec_uri
      - unless @rpm.homepage.blank? || @rpm.homepage == @rpm.source_uri
        %p
          Upstream url:
          = link_to @rpm.homepage, @rpm.homepage
      - unless @rpm.owner.blank?
        %p
          Maintainer:
          = link_to @rpm.owner,
          fedorarpm_path(@rpm.owner + "/by_owner")
      %p
        Git Commits: <strong>#{@rpm.commits}</strong>
      - unless @rpm.last_committer.blank?
        %p
          Last packager: <strong>#{@rpm.last_committer}</strong>
      - unless @rpm.last_commit_message.blank?
        %p
          Last commit message: <strong>#{@rpm.last_commit_message}</strong>
      - unless @rpm.last_commit_date.blank?
        %p
          Last commit date: <strong>#{@rpm.last_commit_date.to_s(:long)}</strong>
      - unless @rpm.description.blank?
        %p
          Description:
          =@rpm.description

    .tab-pane.fade#versions
      .table-responsive
        %table.table.table-hover.table-condensed
          %thead
            %tr.warning
              -FedoraRpm.fedora_versions.each do |t, g|
                %th= t
              %th= _('Gem Version')
          %tbody
            %tr
              -FedoraRpm.fedora_versions.each do |t, g|
                %td= @rpm.version_for(t)
              %td= @rpm.ruby_gem.version

    .tab-pane.fade#dependencies
      %h3
        = link_to 'Dependency Tree', controller: 'fedorarpms',
                                     action: 'full_deps'
      .row
        .col-md-6
          - if @dependencies.blank?
            %h4 No dependencies
          - else
            %h4= "Dependencies: #{@dependencies.count}"

            .table-responsive
              %table.table.table-hover.table-condensed
                %thead
                  %tr.warning
                    %th Package
                    %th Environment
                    -FedoraRpm.fedora_versions.each do |t, g|
                      - if g == 'master'
                        %th= 'Rawhide'
                      - else
                        %th= g
                    %th= _('Upstream')
                %tbody
                  - @dependencies.each do |d|
                    %tr
                      %td= link_to d.name, fedorarpm_path(d.name)
                      %td= @rpm.dependencies.find_by(dependent: d.shortname).environment
                      -FedoraRpm.fedora_versions.each do |t, g|
                        %td= d.version_for(t)
                      %td= d.ruby_gem.version

        %div.col-md-6
          - if @dependents.blank?
            %h4 No dependents
          - else
            %h4= "Dependents: #{@dependents.count}"

            .table-responsive
              %table.table.table-hover.table-condensed
                %thead
                  %tr.warning
                    %th= _('Package')
                    -FedoraRpm.fedora_versions.each do |t, g|
                      - if g == 'master'
                        %th= 'Rawhide'
                      - else
                        %th= g
                    %th= _('Upstream')
                %tbody
                  - @dependents.each do |d|
                    %tr
                      %td= link_to d.name, fedorarpm_path(d.name)
                      -FedoraRpm.fedora_versions.each do |t, g|
                        %td= d.version_for(t)
                      %td= d.ruby_gem.version

    .tab-pane.fade#bugs
      - if @rpm.bugs.blank?
        %h4 No bugs found!
      - else
        .table-responsive
          %table.table.table-hover.table-condensed
            %thead
              %tr.warning
                %th= _('ID')
                %th= _('Title')
            %tbody
              - @rpm.bugs.each do |b|
                %tr
                  %td
                    = link_to b.bz_id, b.url
                  %td
                    = b.name.truncate(60)

    .tab-pane.fade#builds
      .table-responsive
        %table.table.table-hover.table-condensed
          %thead
            %tr.warning
              %th= _('Build ID')
              %th= _('Title')
          %tbody
            - @rpm.koji_builds.each do |b|
              %tr
                %td
                  = link_to b.build_id, b.build_url
                %td
                  = b.name.truncate(60)