config/routes.rb
Isitfedoraruby::Application.routes.draw do

  root to: 'home#show'

  get 'about', to: 'static_pages#about'
  get 'contact', to: 'static_pages#contact'

  get 'searches/suggest_gems' => 'searches#suggest_gems'
  post 'searches/' => 'searches#redirect'
  get 'searches/:id' => 'searches#index'

  resources :fedorarpms, only: [:index, :show] do
    member do
      get :full_deps
      get :full_dependencies
      get :full_dependents
      get :by_owner
      get :badge
      get :not_found
    end
  end

  resources :rubygems, only: [:index, :show]

  resources :stats, only: [:index] do
    get :gemfile_tool, on: :collection
    get :user_rpms
    get :timeline
    get :tljson
    get :user_rpms_data
    post :gemfile_tool, on: :collection
  end

  # unless Rails.application.config.consider_all_requests_local
  get '*not_found', to: 'errors#error_404'
  #  end

end

app/views/layouts/_footer.html.haml
%footer.footer
  %small
    Version
    = Git::VERSION
    @
  %small
    = succeed '-' do
      = link_to "#{Git::REVISION} ",
        "https://github.com/axilleas/isitfedoraruby/commit/#{Git::REVISION}"
  %small
    = precede '-' do
      App last updated
      = Git::DATE
  %nav
    %ul
      %li= link_to _('Contact'), contact_path

app/views/layouts/_header.html.haml
%header.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{ type: 'button', data: {toggle: 'collapse', target: '#header-collapse'}}
        %span.sr-only 'Toggle navigation'
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'FedoraRuby', root_path, class: 'navbar-brand'

    %nav.collapse.navbar-collapse#header-collapse{role: 'navigation'}
      %ul.nav.navbar-nav
        %li{class: is_active?(root_path)}
          = link_to _('Home'), root_path
        %li{class: is_active?(rubygems_path)}
          = link_to _('Ruby Gems'), rubygems_path
        %li{class: is_active?(fedorarpms_path)}
          = link_to _('Fedora Rpms'), fedorarpms_path
        %li{class: is_active?(about_path)}
          = link_to _('About'), about_path

      %ul.nav.navbar-nav.navbar-right
        %li
          = form_tag( { :controller => 'searches', :action => 'redirect' },
          :class => 'navbar-form', :method => 'post') do
            .input-group
              = text_field_tag :search, params[:search] ||= '',
                  class: 'search-query form-control',
                  placeholder: 'Search'
              %span.input-group-btn
                = button_tag raw('<span class="glyphicon glyphicon-search"></span>'), name: nil, class: 'btn btn-default'

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title= "isitFedoraRuby - #{@page_title}"
    %meta{ :content => "width=device-width, initial-scale=1, maximum-scale=1", :name => "viewport" }
    = stylesheet_link_tag "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body
    = render 'layouts/header'
    .container
      = yield
      = render 'layouts/footer'